import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    props: Readonly<{ children: React.ReactNode }>
) {
    return (
        <html lang="en">
            <body className={`${inter.className} p-4`}>
                <h4 className="font-bold mb-4">Root Layout</h4>

                <div className="border-2 border-black rounded">
                    {props.children}
                </div>
            </body>
        </html>
    );
}
